behaviors:
  NormalEnemy:
    trainer_type: ppo
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 1e-3
      beta: 1e-2
      epsilon: 0.2
      lambd: 0.93
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
